development:
  adapter: postgresql
  database: alliance_dev
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: alliance_staging
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: alliance_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: alliance_prod
  pool: 5
  timeout: 5000

cucumber:
  <<: *test